- name: Begin SonarCloud analysis
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    dotnet sonarscanner begin \
      /k:"nhat-trieu_devops-bansach" \
      /o:"nhat-trieu" \
      /d:sonar.host.url="https://sonarcloud.io" \
      /d:sonar.login="$SONAR_TOKEN" \
      /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml"

- name: Restore, Build, and Test with Coverage
  run: |
    dotnet restore Project_BanSach/Project_BanSach.csproj
    dotnet build Project_BanSach/Project_BanSach.csproj -c Release
    dotnet test Project_BanSach/Project_BanSach.csproj --no-build --collect:"XPlat Code Coverage"

- name: End SonarCloud analysis
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
